backup-time: "0 0 * * *"
backup-worlds:
  - world
  - world_nether
  - world_the_end
backup-keep-count: 1

S3:
  enabled: false
  bucket: "your-bucket-name"
  region: "ap-northeast-1"
  storage-class: "your-storage-class"
  upload-prefix: "your-upload-prefix"

  access-key: "your-access-key"
  secret-access-key: "your-secret-access-key"